# Generated by Django 4.2.17 on 2025-02-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetCareRequest',
        ),
    ]
